# Generated by Django 3.1 on 2020-09-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mejora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_mejora', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_patente', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='fabrica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.fabrica'),
        ),
        migrations.AddField(
            model_name='auto',
            name='mejoras',
            field=models.ManyToManyField(to='myapp.Mejora'),
        ),
        migrations.AddField(
            model_name='auto',
            name='patente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patente'),
            preserve_default=False,
        ),
    ]
